name: fvm_go_router_builder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
# sdkは公式に合わせてupdateすること
# https://docs.flutter.dev/install/archive
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.0
  riverpod_annotation: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  go_router_builder: ^4.0.1
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
flutter:
  uses-material-design: true
